"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import EmailButton from "../components/EmailButton";

const LAST_POLICY_KEY = "policysprint:lastPolicy";

export default function QuizPage() {
  const [numQuestions, setNumQuestions] = useState<number>(5);
  const [policyText, setPolicyText] = useState<string>("");
  const [quiz, setQuiz] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [prefilledFromStorage, setPrefilledFromStorage] =
    useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);

  // Auto-generate flags
  const [autoGenerated, setAutoGenerated] = useState<boolean>(false);
  const [autoAttempted, setAutoAttempted] = useState<boolean>(false);

  // Prefill from last generated policy, if present
  useEffect(() => {
    if (typeof window === "undefined") return;
    if (policyText.trim().length > 0) return;

    try {
      const stored = window.localStorage.getItem(LAST_POLICY_KEY);
      if (stored && stored.trim().length > 0) {
        setPolicyText(stored);
        setPrefilledFromStorage(true);
      }
    } catch (err) {
      console.error("Error reading last policy from localStorage", err);
    }
  }, [policyText]);

  // Core generate function (used by auto + manual)
  async function runGenerate(policy: string, count: number, isAuto = false) {
    if (!policy.trim()) {
      setErrorMessage("Please paste or provide your AI Use Policy first.");
      return;
    }

    setErrorMessage(null);
    setQuiz("");
    setLoading(true);
    if (isAuto) {
      setAutoAttempted(true);
      setAutoGenerated(false);
    }

    try {
      const res = await fetch("/api/quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          policyText: policy,
          numQuestions: count,
        }),
      });

      const data = await res.json().catch(() => ({} as any));

      if (!res.ok) {
        throw new Error(data?.error || "Quiz generation failed.");
      }

      if (!data.quiz || typeof data.quiz !== "string") {
        throw new Error("Unexpected response from quiz API.");
      }

      setQuiz(data.quiz);
      if (isAuto) {
        setAutoGenerated(true);
      } else {
        setAutoGenerated(false);
      }
    } catch (err: any) {
      console.error("Error generating quiz:", err);
      setErrorMessage(
        err?.message || "Something went wrong while generating the quiz."
      );
      if (isAuto) {
        setAutoGenerated(false);
      }
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    await runGenerate(policyText, numQuestions, false);
  }

  useEffect(() => {
    if (!prefilledFromStorage) return;
    if (!policyText.trim()) return;
    if (autoAttempted) return;

    void runGenerate(policyText, numQuestions, true);
  }, [prefilledFromStorage, policyText, numQuestions, autoAttempted]);

  async function handleCopyQuiz() {
    if (!quiz) return;
    try {
      await navigator.clipboard.writeText(quiz);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch (err) {
      console.error("Failed to copy quiz text", err);
    }
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <main className="max-w-5xl mx-auto px-4 py-6 md:py-10">
        <div className="space-y-6">
          {/* Top bar (match wizard look) */}
          <header className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div className="flex items-center gap-2">
              <div className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-900 text-xs font-semibold text-white">
                PS
              </div>
              <div>
                <h1 className="text-sm font-semibold text-slate-900">
                  PolicySprint
                </h1>
                <p className="text-xs text-slate-500">
                  Training quiz generator
                </p>
              </div>
            </div>
            <div className="text-[11px] text-slate-500">
              Optional add-on · Turn your policy into a staff quiz
            </div>
          </header>

          {/* Hero / intro card */}
          <section className="bg-white border border-slate-200 rounded-2xl shadow-sm p-5 md:p-6 space-y-4">
            <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
              <div className="space-y-1">
                <h2 className="text-xl md:text-2xl font-semibold text-slate-900">
                  Turn your AI Use Policy into a{" "}
                  <span className="bg-gradient-to-r from-sky-500 to-emerald-500 bg-clip-text text-transparent">
                    staff training quiz
                  </span>
                </h2>
                <p className="text-xs md:text-sm text-slate-600 max-w-xl">
                  Paste your AI Use Policy (or use the pre-filled one from the
                  wizard) and generate a short multiple-choice quiz to check
                  staff understanding.
                </p>
                {prefilledFromStorage && (
                  <p className="text-[11px] text-emerald-700">
                    Loaded your most recent policy from the wizard.{" "}
                    {autoGenerated && !loading && quiz && (
                      <span className="text-emerald-600 font-medium">
                        Quiz auto-generated from that policy.
                      </span>
                    )}
                  </p>
                )}
              </div>

              <div className="flex flex-col items-end gap-1 text-[11px] text-slate-500">
                <Link
                  href="/wizard"
                  className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 font-medium text-slate-600 hover:bg-white hover:border-slate-300"
                >
                  ← Back to policy wizard
                </Link>
                <span>
                  Quiz is a training tool only · not required for the policy
                  itself
                </span>
              </div>
            </div>

            {/* Main grid */}
            <div className="mt-4 grid gap-6 md:grid-cols-[minmax(0,2.1fr),minmax(0,1.9fr)]">
              {/* LEFT: controls & policy input */}
              <form
                onSubmit={handleGenerate}
                className="space-y-4 rounded-xl border border-slate-200 bg-slate-50 p-4"
              >
                <div className="grid grid-cols-[minmax(0,1.4fr),minmax(0,1fr)] gap-3 items-end">
                  <div>
                    <label className="block text-xs font-medium text-slate-700 mb-1">
                      Number of questions
                    </label>
                    <select
                      className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-slate-900"
                      value={numQuestions}
                      onChange={(e) =>
                        setNumQuestions(Number(e.target.value) || 1)
                      }
                    >
                      <option value={3}>3 questions (quick check)</option>
                      <option value={5}>5 questions (short quiz)</option>
                      <option value={8}>8 questions (standard)</option>
                      <option value={10}>10 questions (detailed)</option>
                    </select>
                    <p className="mt-1 text-[11px] text-slate-500">
                      Enough questions to cover key rules without overwhelming
                      people.
                    </p>
                  </div>

                  <div className="flex justify-end">
                    <button
                      type="submit"
                      disabled={loading}
                      className="inline-flex items-center justify-center rounded-full bg-slate-900 px-5 py-2 text-sm font-medium text-white hover:bg-slate-800 disabled:opacity-60"
                    >
                      {loading ? "Generating quiz…" : "Generate quiz"}
                    </button>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-medium text-slate-700 mb-1">
                    AI Use Policy
                  </label>
                  <textarea
                    className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 outline-none focus:border-slate-900 min-h-[180px]"
                    value={policyText}
                    onChange={(e) => {
                      setPolicyText(e.target.value);
                      setAutoGenerated(false);
                    }}
                    placeholder="Paste your full AI Use Policy here, or generate one via the wizard first."
                  />
                  <p className="mt-1 text-[11px] text-slate-500">
                    The quiz will focus on what&apos;s allowed / not allowed,
                    data privacy, tool usage, and who to ask for help.
                  </p>
                </div>

                {errorMessage && (
                  <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-[11px] text-red-700">
                    {errorMessage}
                  </div>
                )}

                {loading && !errorMessage && (
                  <p className="text-[11px] text-slate-500">
                    Drafting questions that match your policy and are clear for
                    staff…
                  </p>
                )}
              </form>

              {/* RIGHT: quiz output */}
              <div className="rounded-xl border border-slate-200 bg-slate-900 text-slate-50 p-4 flex flex-col">
                <div className="flex items-center justify-between mb-2">
                  <div>
                    <h3 className="text-sm font-semibold">
                      Quiz output (plain text)
                    </h3>
                    <p className="text-[11px] text-slate-300">
                      Each question includes answer options A–D and a{" "}
                      <span className="font-semibold">“Correct answer”</span>{" "}
                      line beneath.
                    </p>
                    {autoGenerated && !loading && quiz && (
                      <p className="mt-1 text-[11px] text-emerald-300">
                        Generated automatically from your last policy.
                      </p>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={handleCopyQuiz}
                    disabled={!quiz}
                    className={`rounded-full border px-3 py-1.5 text-[11px] font-medium transition ${
                      quiz
                        ? "border-slate-400 text-slate-50 hover:border-sky-300"
                        : "border-slate-700 text-slate-500 cursor-not-allowed"
                    }`}
                  >
                    {copied ? "Copied!" : "Copy quiz"}
                  </button>
                </div>

                <div className="mb-2">
                  <EmailButton
                    subject="Your AI Use Policy - Training Quiz"
                    getBody={() => quiz || ""}
                    label="Email this quiz"
                    variant="dark"
                  />
                </div>

                <div className="flex-1 rounded-lg border border-slate-700 bg-slate-950/70 p-3 text-xs whitespace-pre-wrap overflow-auto">
                  {!quiz && !loading && !errorMessage && (
                    <p className="text-slate-400">
                      After you generate, your quiz will appear here in plain
                      text:
                      <br />
                      <br />
                      <span className="font-semibold">
                        1. Question text
                      </span>
                      <br />
                      A) Option A
                      <br />
                      B) Option B
                      <br />
                      C) Option C
                      <br />
                      D) Option D
                      <br />
                      Correct answer: B
                      <br />
                      <br />
                      Tip: Paste this into Google Forms, Typeform, your LMS or a
                      simple email for staff.
                    </p>
                  )}
                  {quiz && !loading && quiz}
                  {loading && !quiz && (
                    <p className="text-slate-400 italic">
                      Generating questions that align with your policy…
                    </p>
                  )}
                </div>

                <p className="mt-2 text-[11px] text-slate-400">
                  Tip: Use this quiz after staff read the policy or staff guide.
                  You can also reuse it for onboarding and annual refreshers.
                </p>
              </div>
            </div>
          </section>

          <p className="text-[11px] text-slate-500">
            This quiz is for training only and does not replace formal policy
            sign-off. Always keep a copy of your official AI Use Policy and any
            legal advice you receive.
          </p>
        </div>
      </main>
    </div>
  );
}
