// app/quiz/QuizClient.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import EmailButton from "../components/EmailButton";
import PdfPreviewClient from "../components/PdfPreviewClient";
import DownloadGateCard from "../components/DownloadGateCard";

const LAST_POLICY_KEY = "policysprint:lastPolicy";
const LAST_BUSINESS_KEY = "policysprint:lastBusinessName";

type GateError = {
  ok?: boolean;
  error?: { code?: string; message?: string; details?: any };
};

export default function QuizClient() {
  const [numQuestions, setNumQuestions] = useState<number>(5);
  const [policyText, setPolicyText] = useState<string>("");
  const [quiz, setQuiz] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [prefilledFromStorage, setPrefilledFromStorage] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);

  // Auto-generate flags
  const [autoGenerated, setAutoGenerated] = useState<boolean>(false);
  const [autoAttempted, setAutoAttempted] = useState<boolean>(false);

  // Quiz PDF controls/state
  const [businessName, setBusinessName] = useState<string>("");
  const [quizTitle, setQuizTitle] = useState<string>("AI Use Policy — Staff Quiz");
  const [includeAnswerKey, setIncludeAnswerKey] = useState<boolean>(true);

  const [pdfLoading, setPdfLoading] = useState<boolean>(false);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [pdfError, setPdfError] = useState<string | null>(null);
  const [downloadingPdf, setDownloadingPdf] = useState<boolean>(false);

  // ✅ Download-only gating (match other pages: upgrade banner only)
  const [upgradeRequired, setUpgradeRequired] = useState<boolean>(false);

  const canBuildPdf = useMemo(() => quiz.trim().length > 0, [quiz]);

  // Prefill from last generated policy
  useEffect(() => {
    if (typeof window === "undefined") return;

    if (policyText.trim().length === 0) {
      try {
        const stored = window.localStorage.getItem(LAST_POLICY_KEY);
        if (stored && stored.trim().length > 0) {
          setPolicyText(stored);
          setPrefilledFromStorage(true);
        }
      } catch (err) {
        console.error("Error reading last policy from localStorage", err);
      }
    }

    if (businessName.trim().length === 0) {
      try {
        const bn = window.localStorage.getItem(LAST_BUSINESS_KEY);
        if (bn && bn.trim().length > 0) setBusinessName(bn);
      } catch {}
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Cleanup blob URL on unmount
  useEffect(() => {
    return () => {
      if (pdfUrl) URL.revokeObjectURL(pdfUrl);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function runGenerate(policy: string, count: number, isAuto = false) {
    if (!policy.trim()) {
      setErrorMessage("Please paste or provide your AI Use Policy first.");
      return;
    }

    setErrorMessage(null);
    setQuiz("");
    setCopied(false);
    setLoading(true);

    // Reset PDF preview whenever we regenerate quiz
    setPdfError(null);
    setUpgradeRequired(false);
    if (pdfUrl) URL.revokeObjectURL(pdfUrl);
    setPdfUrl(null);

    if (isAuto) {
      setAutoAttempted(true);
      setAutoGenerated(false);
    }

    try {
      const res = await fetch("/api/quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          policyText: policy,
          numQuestions: count,
        }),
      });

      const data = await res.json().catch(() => ({} as any));

      if (!res.ok) {
        throw new Error(data?.error || "Quiz generation failed.");
      }

      if (!data.quiz || typeof data.quiz !== "string") {
        throw new Error("Unexpected response from quiz API.");
      }

      setQuiz(data.quiz);
      setAutoGenerated(isAuto);
    } catch (err: any) {
      console.error("Error generating quiz:", err);
      setErrorMessage(err?.message || "Something went wrong while generating the quiz.");
      if (isAuto) setAutoGenerated(false);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    await runGenerate(policyText, numQuestions, false);
  }

  // Auto-generate quiz once if loaded from storage
  useEffect(() => {
    if (!prefilledFromStorage) return;
    if (!policyText.trim()) return;
    if (autoAttempted) return;

    void runGenerate(policyText, numQuestions, true);
  }, [prefilledFromStorage, policyText, numQuestions, autoAttempted]);

  async function handleCopyQuiz() {
    if (!quiz) return;
    try {
      await navigator.clipboard.writeText(quiz);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch (err) {
      console.error("Failed to copy quiz text", err);
    }
  }

  async function buildQuizPdf(mode: "preview" | "download") {
    if (!quiz.trim()) return;

    setPdfLoading(mode === "preview");
    setDownloadingPdf(mode === "download");
    setPdfError(null);

    if (mode === "download") {
      // Only clear banner when trying again
      setUpgradeRequired(false);
    }

    // Persist business name
    try {
      if (typeof window !== "undefined" && businessName.trim()) {
        window.localStorage.setItem(LAST_BUSINESS_KEY, businessName.trim());
      }
    } catch {}

    try {
      const payload = {
        title: quizTitle?.trim() ? quizTitle.trim() : "AI Use Policy — Staff Quiz",
        businessName: businessName?.trim() ? businessName.trim() : "Your business",
        quizText: quiz,
        includeAnswerKey,
      };

      const res = await fetch("/api/quiz-pdf", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-pdf-mode": mode,
        },
        body: JSON.stringify(payload),
      });

      // ✅ Map EMAIL_NOT_VERIFIED to upgrade banner (match other pages)
      if (res.status === 403) {
        let parsed: GateError | null = null;
        try {
          parsed = (await res.json()) as GateError;
        } catch {}

        const code = typeof parsed?.error?.code === "string" ? parsed!.error!.code : "";
        const msg = typeof parsed?.error?.message === "string" ? parsed!.error!.message : "";

        if (mode === "download") {
          // Treat both of these as "upgrade required" for quiz downloads
          if (code === "PRO_REQUIRED" || code === "EMAIL_NOT_VERIFIED") {
            setUpgradeRequired(true);
            return;
          }
        }

        throw new Error(msg || "Forbidden.");
      }

      if (!res.ok) {
        const txt = await res.text().catch(() => "");
        throw new Error(txt?.trim() ? txt.slice(0, 240) : "Failed to generate quiz PDF.");
      }

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);

      if (mode === "download") {
        const safeName = (businessName?.trim() ? businessName.trim() : "quiz")
          .replace(/\s+/g, "-")
          .toLowerCase()
          .replace(/[^a-z0-9\-]/g, "");

        const a = document.createElement("a");
        a.href = url;
        a.download = `${safeName || "quiz"}-staff-quiz.pdf`;
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(url);
        return;
      }

      // mode === preview
      setPdfUrl((old) => {
        if (old) URL.revokeObjectURL(old);
        return url;
      });
    } catch (err: any) {
      console.error("Quiz PDF error:", err);
      setPdfError(err?.message || "Failed to generate quiz PDF.");
    } finally {
      setPdfLoading(false);
      setDownloadingPdf(false);
    }
  }

  // Auto-build preview after quiz exists (one time)
  useEffect(() => {
    if (!quiz.trim()) return;
    if (pdfUrl) return;
    if (pdfLoading) return;
    if (pdfError) return;

    void buildQuizPdf("preview");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [quiz]);

  // ---------- Styles (match Wizard) ----------
  const card = "rounded-2xl border border-slate-800 bg-slate-900/40 p-5 md:p-6 shadow-sm";
  const label = "block text-xs font-medium text-slate-200 mb-1";
  const hint = "text-[11px] text-slate-400";
  const input =
    "w-full rounded-xl border border-slate-700 bg-slate-950/60 px-4 py-3 text-sm text-slate-100 placeholder:text-slate-500 outline-none focus:ring-2 focus:ring-emerald-400/40";
  const inputSm =
    "w-full rounded-xl border border-slate-700 bg-slate-950/60 px-4 py-2.5 text-sm text-slate-100 placeholder:text-slate-500 outline-none focus:ring-2 focus:ring-emerald-400/40";
  const btnPrimary =
    "inline-flex items-center justify-center rounded-full bg-slate-50 px-5 py-2 text-sm font-medium text-slate-950 hover:bg-slate-200 disabled:opacity-60";
  const btnSecondary =
    "inline-flex items-center justify-center rounded-full border border-slate-600 px-4 py-2 text-[11px] text-slate-100 hover:bg-slate-900/60 disabled:opacity-60";
  const btnMini =
    "inline-flex items-center justify-center rounded-full border border-slate-700 bg-slate-900/40 px-3 py-1.5 text-[11px] text-slate-100 hover:bg-slate-900/70 disabled:opacity-60";

  const showGateCard = upgradeRequired;

  return (
    <main className="min-h-screen bg-slate-950 text-slate-50">
      {/* ✅ padding so sticky global Header doesn't crowd content */}
      <div className="mx-auto max-w-5xl px-4 pt-6 pb-6 md:pt-10 md:pb-10">
        <div className="space-y-4">
          {/* Intro */}
          <section className={`${card} space-y-3`}>
            <div className="flex items-start justify-between gap-3">
              <div>
                <h1 className="text-xl md:text-2xl font-semibold text-slate-50 mb-1">Staff training quiz</h1>
                <p className="text-xs md:text-sm text-slate-300 max-w-2xl">
                  Generate multiple-choice questions from your AI Use Policy, then export a polished PDF for onboarding,
                  annual refreshers, or staff sign-off packs.
                </p>

                {prefilledFromStorage ? (
                  <p className="mt-2 text-[11px] text-emerald-300">
                    Loaded your most recent policy from the wizard.
                    {autoGenerated && quiz && !loading ? (
                      <span className="text-emerald-200 font-medium"> Quiz auto-generated.</span>
                    ) : null}
                  </p>
                ) : (
                  <p className="mt-2 text-[11px] text-slate-400">
                    Tip: generate a policy in the wizard first, then come back here.
                  </p>
                )}
              </div>

              <div className="shrink-0">
                <Link href="/wizard" className={btnSecondary}>
                  ← Back to wizard
                </Link>
              </div>
            </div>
          </section>

          {/* Main grid */}
          <div className="grid md:grid-cols-[3fr,2fr] gap-4">
            {/* LEFT: inputs + quiz output */}
            <section className={`${card} space-y-4`}>
              <form className="space-y-4" onSubmit={handleGenerate}>
                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <label className={label}>Number of questions</label>
                    <select
                      className={inputSm}
                      value={numQuestions}
                      onChange={(e) => setNumQuestions(Number(e.target.value) || 1)}
                    >
                      <option value={3}>3 questions (quick check)</option>
                      <option value={5}>5 questions (short quiz)</option>
                      <option value={8}>8 questions (standard)</option>
                      <option value={10}>10 questions (detailed)</option>
                      <option value={15}>15 questions (more thorough)</option>
                      <option value={20}>20 questions (training pack)</option>
                      <option value={25}>25 questions (max)</option>
                    </select>
                    <p className={`${hint} mt-1`}>We cap at 25 to keep output readable.</p>
                  </div>

                  <div className="flex items-end justify-end">
                    <button type="submit" className={btnPrimary} disabled={loading}>
                      {loading ? "Generating…" : "Generate quiz →"}
                    </button>
                  </div>
                </div>

                <div>
                  <label className={label}>AI Use Policy</label>
                  <textarea
                    className={input}
                    rows={10}
                    value={policyText}
                    onChange={(e) => {
                      setPolicyText(e.target.value);
                      setAutoGenerated(false);
                    }}
                    placeholder="Paste your full AI Use Policy here (or generate one via the wizard)."
                  />
                  <p className={`${hint} mt-1`}>
                    The quiz focuses on allowed use, data handling, approvals, and escalation paths.
                  </p>
                </div>

                {errorMessage ? (
                  <div className="rounded-xl border border-rose-900/40 bg-rose-950/30 px-4 py-3 text-[11px] text-rose-200">
                    {errorMessage}
                  </div>
                ) : null}

                {loading && !errorMessage ? (
                  <div className="text-[11px] text-slate-400">
                    Drafting questions that match your policy and are clear for staff…
                  </div>
                ) : null}
              </form>

              {/* Quiz output */}
              <div className="rounded-xl border border-slate-800 bg-slate-950/40 p-3">
                <div className="flex items-start justify-between gap-3 mb-2">
                  <div>
                    <div className="text-[11px] font-semibold text-slate-100">Quiz output</div>
                    <div className="text-[10px] text-slate-400">
                      Includes answer options A–D and a{" "}
                      <span className="font-semibold text-slate-200">Correct answer</span> line.
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <button type="button" onClick={handleCopyQuiz} disabled={!quiz} className={btnMini}>
                      {copied ? "Copied!" : "Copy quiz"}
                    </button>
                  </div>
                </div>

                <div className="mb-2">
                  <EmailButton
                    subject="AI Use Policy — Training Quiz"
                    getBody={() => quiz || ""}
                    label="Email this quiz"
                    variant="dark"
                  />
                </div>

                <div className="h-72 rounded-xl border border-slate-800 bg-slate-950/70 px-4 py-3 text-[11px] leading-relaxed text-slate-100 whitespace-pre-wrap overflow-auto">
                  {!quiz && !loading && !errorMessage ? (
                    <div className="text-slate-400">
                      Generate a quiz and it will appear here.
                      <br />
                      <br />
                      <span className="font-semibold text-slate-200">Example format:</span>
                      <br />
                      <br />
                      1. Question text
                      <br />
                      A) Option A
                      <br />
                      B) Option B
                      <br />
                      C) Option C
                      <br />
                      D) Option D
                      <br />
                      Correct answer: B
                    </div>
                  ) : null}

                  {loading && !quiz ? <div className="text-slate-400 italic">Generating questions that align with your policy…</div> : null}

                  {quiz && !loading ? quiz : null}
                </div>

                <p className={`${hint} mt-2`}>Tip: paste into Google Forms, Typeform, or your LMS. Or export a PDF below.</p>
              </div>
            </section>

            {/* RIGHT: PDF panel */}
            <section className={`${card} space-y-3`}>
              <div>
                <h2 className="text-sm font-semibold text-slate-100">Quiz PDF</h2>
                <p className="text-[11px] text-slate-400">Styled PDF with cover, questions and (optional) answer key.</p>
              </div>

              <div className="space-y-3">
                <div>
                  <label className={label}>Business name</label>
                  <input
                    className={inputSm}
                    value={businessName}
                    onChange={(e) => setBusinessName(e.target.value)}
                    placeholder="e.g. Bondi Physio Clinic"
                  />
                </div>

                <div>
                  <label className={label}>Quiz title</label>
                  <input
                    className={inputSm}
                    value={quizTitle}
                    onChange={(e) => setQuizTitle(e.target.value)}
                    placeholder="AI Use Policy — Staff Quiz"
                  />
                </div>

                <div className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950/40 px-3 py-2">
                  <div>
                    <div className="text-[11px] font-medium text-slate-100">Include answer key</div>
                    <div className="text-[10px] text-slate-400">Adds a final page with correct answers.</div>
                  </div>
                  <button
                    type="button"
                    onClick={() => setIncludeAnswerKey((v) => !v)}
                    className={[
                      "rounded-full border px-3 py-1 text-[11px] transition",
                      includeAnswerKey
                        ? "border-emerald-400/30 bg-emerald-950/20 text-emerald-200"
                        : "border-slate-700 bg-slate-950/40 text-slate-200 hover:bg-slate-900/50",
                    ].join(" ")}
                  >
                    {includeAnswerKey ? "On" : "Off"}
                  </button>
                </div>

                {/* ✅ Upgrade-only gate card */}
                {showGateCard ? (
                  <DownloadGateCard
                    showUpgrade
                    title="Downloads are locked"
                    subtitle="Preview works — downloads require Pro."
                  />
                ) : null}

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => buildQuizPdf("preview")}
                    disabled={!canBuildPdf || pdfLoading}
                    className={btnSecondary}
                  >
                    {pdfLoading ? "Building…" : "Refresh preview"}
                  </button>

                  <button
                    type="button"
                    onClick={() => buildQuizPdf("download")}
                    disabled={!canBuildPdf || downloadingPdf}
                    className={btnSecondary}
                  >
                    {downloadingPdf ? "Preparing…" : "Download PDF"}
                  </button>
                </div>

                {pdfError ? (
                  <div className="rounded-xl border border-rose-900/40 bg-rose-950/30 px-4 py-3 text-[11px] text-rose-200">
                    {pdfError}
                  </div>
                ) : null}

                <div className="rounded-xl border border-slate-800 bg-slate-950/40 p-3">
                  <div className="flex items-center justify-between gap-3 mb-2">
                    <div>
                      <div className="text-[11px] font-semibold text-slate-100">PDF preview</div>
                      <div className="text-[10px] text-slate-400">Preview uses an inline watermark.</div>
                    </div>
                  </div>

                  <PdfPreviewClient blobUrl={pdfUrl} loading={pdfLoading} error={pdfError} height={520} />
                </div>
              </div>

              <div className="rounded-xl border border-slate-800 bg-slate-950/40 px-3 py-2">
                <div className="text-[11px] font-medium text-slate-100 mb-1">Suggested use</div>
                <ul className="list-disc pl-4 text-[11px] text-slate-300 space-y-1">
                  <li>Send after staff read the policy or staff guide</li>
                  <li>Use for onboarding + annual refreshers</li>
                  <li>Store signed completion evidence in HR/LMS</li>
                </ul>
              </div>
            </section>
          </div>

          <p className="text-[11px] text-slate-500">
            Training tool only — not legal advice. Always keep your official AI Use Policy and any legal/compliance sign-off on file.
          </p>
        </div>
      </div>
    </main>
  );
}
