// lib/prisma.ts

// Prisma 7 + better-sqlite3 adapter
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
// @ts-ignore PrismaClient is generated by `prisma generate` and exists at runtime,
// but TypeScript can sometimes not see it correctly in certain build environments.
import { PrismaClient } from "@prisma/client";

// In dev, keep a single PrismaClient instance across HMR reloads.
// In prod (Vercel), a new client is fine per lambda.
const globalForPrisma = globalThis as unknown as {
  prisma?: PrismaClient;
};

const adapter = new PrismaBetterSqlite3();

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    adapter,
  });

// Avoid creating multiple clients in development
if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
