import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";

// Make sure this route runs in the Node.js runtime (required for pdfkit)
export const runtime = "nodejs";

type PolicyPdfPayload = {
  businessName?: string;
  country?: string;
  industry?: string;
  policyText?: string;
};

function createPolicyPdf({
  businessName,
  country,
  industry,
  policyText,
}: {
  businessName: string;
  country: string;
  industry: string;
  policyText: string;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    // pdfkit's type definitions can be a bit loose; "any" keeps TS happy here.
    const doc: any = new PDFDocument({
      size: "A4",
      margin: 56, // ~2cm
      info: {
        Title: businessName
          ? `${businessName} – AI Use Policy`
          : "AI Use & Governance Policy",
        Author: "PolicySprint AI",
      },
    });

    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => {
      chunks.push(chunk);
    });

    doc.on("end", () => {
      try {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      } catch (err) {
        reject(err);
      }
    });

    doc.on("error", (err: any) => {
      reject(err);
    });

    // -------------------------
    // Header / Title section
    // -------------------------
    doc.fontSize(10).fillColor("#64748B").text("PolicySprint AI", {
      align: "left",
    });

    doc.moveDown(0.5);

    const titleText = businessName
      ? `${businessName} – AI Use Policy`
      : "AI Use & Governance Policy";

    doc
      .fontSize(20)
      .fillColor("#0F172A")
      .text(titleText, {
        align: "left",
      });

    doc.moveDown(0.5);

    // Meta info
    const metaLines: string[] = [];
    if (industry) metaLines.push(industry);
    if (country) metaLines.push(country);

    if (metaLines.length > 0) {
      doc
        .fontSize(11)
        .fillColor("#475569")
        .text(metaLines.join(" · "), { align: "left" });
      doc.moveDown(0.25);
    }

    const now = new Date();
    const formattedDate = now.toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });

    doc
      .fontSize(9)
      .fillColor("#64748B")
      .text(`Generated by PolicySprint AI on ${formattedDate}`, {
        align: "left",
      });

    doc.moveDown(1);

    // Divider
    doc
      .moveTo(doc.page.margins.left, doc.y)
      .lineTo(doc.page.width - doc.page.margins.right, doc.y)
      .lineWidth(0.5)
      .strokeColor("#E2E8F0")
      .stroke();

    doc.moveDown(1);

    // -------------------------
    // Policy body
    // -------------------------
    doc.fontSize(11).fillColor("#0F172A");

    const lines = policyText.split("\n");

    for (const line of lines) {
      const trimmed = line.trim();

      if (!trimmed) {
        // Blank line -> add some vertical space
        doc.moveDown(0.5);
        continue;
      }

      // Simple heuristic: if line looks like a numbered heading, make it bold-ish
      if (/^\d+(\.\d+)*[.)]?\s/.test(trimmed) || /^[A-Z][A-Za-z0-9\s]{0,60}$/.test(trimmed)) {
        doc
          .moveDown(0.4)
          .fontSize(12)
          .fillColor("#0F172A")
          .text(trimmed, { underline: false, continued: false });

        doc.moveDown(0.1);
        doc.fontSize(11).fillColor("#0F172A");
      } else {
        doc.text(trimmed, {
          align: "left",
          lineGap: 2,
        });
      }
    }

    doc.end();
  });
}

export async function POST(req: NextRequest) {
  try {
    const body: PolicyPdfPayload = await req.json().catch(() => ({} as PolicyPdfPayload));

    const businessName = body.businessName?.trim() || "";
    const country = body.country?.trim() || "";
    const industry = body.industry?.trim() || "";
    const policyText = body.policyText ?? "";

    if (!policyText || policyText.trim().length === 0) {
      return NextResponse.json(
        { error: "policyText is required to generate a PDF." },
        { status: 400 },
      );
    }

    const pdfBuffer = await createPolicyPdf({
      businessName,
      country,
      industry,
      policyText,
    });

    const safeName =
      businessName.trim().length > 0
        ? businessName.replace(/\s+/g, "-").toLowerCase()
        : "ai-use-policy";

    return new NextResponse(pdfBuffer as any, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${safeName}.pdf"`,
      },
    });
  } catch (error) {
    console.error("[POST /api/policy-pdf] error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF." },
      { status: 500 },
    );
  }
}
